export GIT_BYPASS = 1

# Define Firmware Version Number
export PRJ_VERSION = 0x00000001

# Define the Hardware Type in the axi-pcie-core
export PCIE_HW_TYPE = PgpCardG3

# Define target part
export PRJ_PART = XC7A200TFFG1156-3

# Define target output
target: prom

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
