##############################################################################
## This file is part of 'PGP PCIe APP DEV'.
## It is subject to the license terms in the LICENSE.txt file found in the
## top-level directory of this distribution and at:
##    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
## No part of 'PGP PCIe APP DEV', including this file,
## may be copied, modified, propagated, or distributed except according to
## the terms contained in the LICENSE.txt file.
##############################################################################

#######################
# Placement Constraints
#######################

set_property USER_SLR_ASSIGNMENT SLR1 [get_cells {U_Hardware}]
set_property USER_SLR_ASSIGNMENT SLR0 [get_cells {U_HbmDmaBuffer}]

# SLR1: Left Side = NORTH_WEST_GRP (region defined in XilinxAlveoU55cCore.xdc)
add_cells_to_pblock [get_pblocks NORTH_WEST_GRP] [get_cells [list U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4]]
add_cells_to_pblock [get_pblocks NORTH_WEST_GRP] [get_cells [list U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4]]

# SLR1: Right Side = NORTH_EAST_GRP (region defined in XilinxAlveoU55cCore.xdc)

# SLR0: Left Side = SOUTH_WEST_GRP (region defined in XilinxAlveoU55cCore.xdc)
add_cells_to_pblock [get_pblocks SOUTH_WEST_GRP] [get_cells [list U_HbmDmaBuffer/GEN_FIFO[0].U_HbmAxiFifo]]

# SLR0: Right Side = SOUTH_EAST_GRP (region defined in XilinxAlveoU55cCore.xdc)
add_cells_to_pblock [get_pblocks SOUTH_EAST_GRP] [get_cells [list U_HbmDmaBuffer/GEN_FIFO[1].U_HbmAxiFifo]]

######################
# Timing Constraints #
######################

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U_axilClk/MmcmGen.U_Mmcm/CLKOUT0]] -group [get_clocks hbmRefClkP]

create_clock -period 6.4 -name qsfp0RefClkP [get_ports {qsfp0RefClkP}] ;# SI5394_INIT_FILE_G="Si5394A_GT_REFCLK_156MHz.mem"
create_clock -period 6.4 -name qsfp1RefClkP [get_ports {qsfp1RefClkP}] ;# SI5394_INIT_FILE_G="Si5394A_GT_REFCLK_156MHz.mem"

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/U_phyClk/PllGen.U_Pll/CLKOUT0]] -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/U_phyClk/PllGen.U_Pll/CLKOUT0]] -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[1].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[1].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/RXOUTCLK}]] -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP0/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/RXOUTCLK}]] -group [get_clocks -of_objects [get_pins {U_Hardware/U_QSFP1/U_Htsp/REAL_HTSP.U_IP/USE_REFCLK156MHz.U_CAUI4/inst/Caui4GtyIpCore156MHz_gt_i/inst/gen_gtwizard_gtye4_top.Caui4GtyIpCore156MHz_gt_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[35].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]
