# Define Firmware Version Number
export PRJ_VERSION = 0x00000001

# Use top level makefile
include ../../submodules/vcu1525-static-release/static_config.mk
include ../../submodules/ruckus/system_vivado.mk
