export GIT_BYPASS = 1

# Define Firmware Version Number
export PRJ_VERSION = 0x00000001

# Use top level makefile
include ../../submodules/axi-pcie-core/hardware/XilinxVcu1525/dynamic/config.mk
include ../../submodules/ruckus/system_vivado.mk
